### ISSUE TITLE
Add function (checkbox) "Show only tag changes" for the relation view

### ISSUE THREAD

**Issue by sun-geo** [PeWu/osm-history#10]
As written in the title.
The button text could also be "hide member-changes only" for the relation view to hide the lines of versions where only changes happened on the member list.

**Comment by PeWu** [comment]
Can you verify that the change does what you wanted?
The new version is already published.

**Comment by sun-geo** [comment]
Great, you implemented exactly the idea i had.
It works even for nodes and ways, what I didn't had in my mind. :-)
