### ISSUE TITLE
Suggestion: JOSM link should open in new window

### ISSUE THREAD

**Issue by rory** [PeWu/osm-history#5]
I suggest making the JOSM link open in a new window, since you never really want to actually see the result of the JOSM call, all it does is tell JOSM to open something

**Comment by PeWu** [comment]
The JOSM link is already configured to open in a new tab: <a target="_blank">
Does it open in the same tab for you? What browser are you using?

**Comment by rory** [comment]
Whoops! 🤦 You're right. My mistake.
