### ISSUE TITLE
Add relation membership support for nodes and ways

### ISSUE THREAD

**Issue by tilmanb** [PeWu/osm-history#6]
Nodes and ways (and probably relations, not sure) could also display differences in relation membership from version to version.

**Comment by tyrasd** [comment]
AFAIK there is not publicly available API that returns such information. Or is there?

PS: Btw: Note that the membership of (for example) a way in a relation can change even if the version of the way didn't change.

**Comment by PeWu** [comment]
The OSM API does not support querying historical data of membership, only the current membership. Also, as Martin noted, a change in the membership of a node/way in a way/relation does not change the first one's version.

**Comment by tilmanb** [comment]
seems unfixable
