### ISSUE TITLE
frozen display / high cpu consumption after opening certain osm-objects

### ISSUE THREAD

**Issue by my-na-me** [PeWu/osm-history#7]
Hi, thanks for writing/implementing this amazing tool. I prefer to use pewu/osm-history more frequently than https://osmlab.github.io/osm-deep-history, because the history-list of versions which is shown in vertical direction instead of osmlab.github.io/osm-deep-history which used horizontal direction...

Btw, I noticed two opportunities ;-) (issues) for displaying osm-object-information. 

This happens ( * frozen display, high cpu consumption) for objects which seems to have a very long history(high amount of version-number), I saw for example at national bicycle route relations.  
Unfortunately, for the moment I haven't an example rel-id, but I will add later, once I notice it next time.

Now I also found similar behavior* for way-object (w587855185) which has a small number of object versions (#v5): see https://pewu.github.io/osm-history/#/way/587855185

Could you please check, if w587855185 will be display on your machine? (I used browsers FF or Chromium at Win7)

Thanks for reading.

**Comment by my-na-me** [comment]
Another example for a way object (27892790):
v4: https://pewu.github.io/osm-history/#/way/27892790

**Comment by PeWu** [comment]
Thanks for the bug report. I debugged the issue and made a fix for the problem with small number of objects.
@my-na-me can you verify that it is fixed now?

Let me know when you have an example with a very long history that doesn't work.

**Comment by my-na-me** [comment]
I checked both links:
https://pewu.github.io/osm-history/#/way/587855185
https://pewu.github.io/osm-history/#/way/27892790
and I verify both are working fine without frozen display. Thanks for quick fix! :-)  
  
  
As requested, an object with higher amount of version steps:
https://pewu.github.io/osm-history/#/way/35281608
by opening with FF(error msg): 
![ff](https://user-images.githubusercontent.com/27923772/42631012-3907227c-85d9-11e8-9e3e-06d79549df94.jpg)
by opening with Chromium(frozen display & high cpu consumption & no map display for each history version):
![c](https://user-images.githubusercontent.com/27923772/42631169-a0a7380e-85d9-11e8-91f4-6f99fa196927.jpg)

**Comment by my-na-me** [comment]
closed by mistake => reopened

**Comment by PeWu** [comment]
https://pewu.github.io/osm-history/#/way/35281608 should be fixed now.
Let me know if you find any more such cases.

**Comment by my-na-me** [comment]
Sorry for late reply.
Yes, no frozen situation noticed anymore. :-)
I closed this ticket.

**Comment by my-na-me** [comment]
By the way, JOSM has add a link to this viewer :-)
see: https://josm.openstreetmap.de/ticket/17000
